### ISSUE TITLE
python超新手求教，windows環境下怎麼改code? 一直下載失敗QQ

### ISSUE THREAD

**Issue by koerrrrr** [haward79/porn_video_downloader#1]
如題

**Comment by haward79** [comment]
我在 Windows 11 上測試沒有問題。
請提供錯誤訊息、系統環境、以及載不下來的影片網址。

**Comment by koerrrrr** [comment]
系統環境是Win11 x64
<img width="209" alt="image" src="https://github.com/haward79/porn_video_downloader/assets/147687022/b3fedda4-8822-4411-85ca-6c480c1bf296">

下載的網址是 https://missav.com/video/411972/zipang-15542.html

2023-10-13 11:31:06,732|DEBUG|Loading url "https://missav.com/video/411972/zipang-15542.html" .
2023-10-13 11:31:16,881|DEBUG|Failed to get video url. The url is empty.
2023-10-13 11:31:20,956|INFO|Download video failed.

**Comment by haward79** [comment]
> 系統環境是Win11 x64 <img alt="image" width="209" src="https://user-images.githubusercontent.com/147687022/274788453-b3fedda4-8822-4411-85ca-6c480c1bf296.png">
> 
> 下載的網址是 https://missav.com/video/411972/zipang-15542.html
> 
> 2023-10-13 11:31:06,732|DEBUG|Loading url "https://missav.com/video/411972/zipang-15542.html" . 2023-10-13 11:31:16,881|DEBUG|Failed to get video url. The url is empty. 2023-10-13 11:31:20,956|INFO|Download video failed.

根據檢查，你提供的網址確實無法正常下載。
下載失敗的原因是由於程式碼中含有 bug，請等待下個版本的修正程式碼發佈。

**Comment by koerrrrr** [comment]
謝謝版主的回覆！
我曾經試過許多方式抓取影片的url，不過都失敗告終。

**Comment by haward79** [comment]
> 謝謝版主的回覆！ 我曾經試過許多方式抓取影片的url，不過都失敗告終。

之前提到的問題已在新版程式中修正，missav網站的影片已可正常下載。
不過你之前提供的那個影片仍無法下載，因為該影片檔案似乎掛了，連在原本的網頁中都無法正常播放。
另外，若要使用 Windows 執行本程式，建議手動輸入影片檔名，因為自動取得的影片檔名常常含有Windows無法接受的字元。
